Repository package-Twelve/public_class_Dev, pull requests merged in 2024-08, with the labels that each got.

#103 [Task] 프론트와 연결을 위한 리펙토링 #94
  http/코드 실행.http
  http/코드카타.http
  http/팀매칭.http
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRoomUsers.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRooms.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/ChatRoomsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/controller/CodeKatasController.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/service/CodeKatasService.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/repository/CodeRunsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
  src/main/java/com/sparta/publicclassdev/domain/winners/entity/Winners.java
  src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/winners/service/WinnersService.java
  src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
  src/main/java/com/sparta/publicclassdev/global/config/WebSocketConfig.java
  src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
  src/main/java/com/sparta/publicclassdev/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/publicclassdev/quartz/config/QuartzConfig.java
  src/main/resources/logback-spring.xml
Labels: refactor

#112 코드카타 삭제 시 연관관계 재설정
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/entity/CodeRuns.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/service/CodeRunsService.java
Labels: fix

#113 🩹 fix : 오늘의 코드카타 삭제 시 발생하는 연관관계 오류 수정
  src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
Labels: fix

#115 [Task] 실시간 채팅 저장 안되는 문제 해결 #114
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/controller/ChatRoomsController.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/ChatRoomsDto.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/ChatRoomsRequestDto.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/ChatRoomsResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/MessagesRequestDto.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/MessagesResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsService.java
  src/main/java/com/sparta/publicclassdev/global/config/RedisSubscriber.java
  src/main/java/com/sparta/publicclassdev/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/publicclassdev/global/config/WebSocketSecurityConfig.java
  src/test/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsServiceTest.java
Labels: fix

#119 [2024-08-07] fix/#118-reissue-token-fix >> 토큰 재발급 문제 해결
  src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
  src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
  src/main/java/com/sparta/publicclassdev/global/config/CacheConfig.java
Labels: fix

#122 🩹 fix : codekata contents컬럼을 text로 변경
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
Labels: refactor

#130 ♻️ refactor : 로그 및 주석 제거
  src/main/java/com/sparta/publicclassdev/PublicClassDevApplication.java
  src/main/java/com/sparta/publicclassdev/batch/config/BatchConfig.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/controller/ChatRoomsController.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRoomUsers.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRooms.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/MessagesRepository.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
  src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/dto/CodeReviewCommentsRequestDto.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/entity/CodeRuns.java
  src/main/java/com/sparta/publicclassdev/domain/communities/component/CleanUpScheduler.java
  src/main/java/com/sparta/publicclassdev/domain/communities/dto/CommunitiesRequestDto.java
  src/main/java/com/sparta/publicclassdev/domain/communities/service/CommunitiesService.java
  src/main/java/com/sparta/publicclassdev/domain/communitycomments/service/CommunityCommentsService.java
  src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
  src/main/java/com/sparta/publicclassdev/domain/teams/dto/TeamResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/users/controller/UsersController.java
  src/main/java/com/sparta/publicclassdev/domain/users/repository/UsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/users/service/UsersService.java
  src/main/java/com/sparta/publicclassdev/domain/winners/dto/WinnersResponseDto.java
  src/main/java/com/sparta/publicclassdev/global/CacheNames.java
  src/main/java/com/sparta/publicclassdev/global/config/CacheConfig.java
  src/main/java/com/sparta/publicclassdev/global/config/RedisSubscriber.java
  src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
  src/main/java/com/sparta/publicclassdev/global/config/WebMvcConfig.java
  src/main/java/com/sparta/publicclassdev/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/publicclassdev/global/exception/CustomException.java
  src/main/java/com/sparta/publicclassdev/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/publicclassdev/global/security/JwtUtil.java
  src/main/java/com/sparta/publicclassdev/quartz/job/DailyCodeKataJob.java
  src/test/java/com/sparta/publicclassdev/domain/codereview/CodeReviewsRepositoryTest.java
Labels: refactor

#133 ♻️ refactor : 코드 실행 시 실행가능시간 제한, 금지 코드 추가
  src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaCodeRunner.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaScriptCodeRunner.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/PythonCodeRunner.java
  src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
Labels: refactor

#134 🩹 fix : java실행이 안되던 문제 해결
  src/main/java/com/sparta/publicclassdev/domain/coderuns/runner/JavaCodeRunner.java
Labels: fix

#141 코드 입력 받트는 부분 Valid 추가
  src/main/java/com/sparta/publicclassdev/domain/coderuns/controller/CodeRunsController.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/dto/CodeRunsRequestDto.java
Labels: fix

#143 [Refactor] 팀 서비스 줄맞춤이 안되있던 부분 수정
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/TeamUsers.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
  src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
Labels: refactor

#146 [Feat] 우승자 생성과 삭제 기능 추가 #145
  src/main/java/com/sparta/publicclassdev/domain/winners/controller/WinnersController.java
  src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/winners/service/WinnersService.java
  src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
Labels: feat

#151 [Test]코드카타 테스트 코드 작성
  build.gradle
  src/test/java/com/sparta/publicclassdev/TestConfig.java
  src/test/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsServiceTest.java
  src/test/java/com/sparta/publicclassdev/domain/codekatas/controller/CodeKatasControllerTest.java
  src/test/java/com/sparta/publicclassdev/domain/codekatas/repository/CodeKatasRepositoryTest.java
  src/test/java/com/sparta/publicclassdev/domain/codekatas/service/CodeKatasIntegrationTest.java
  src/test/java/com/sparta/publicclassdev/domain/codekatas/service/CodeKatasServiceTest.java
Labels: test
