Repository package-Twelve/public_class_Dev, pull requests merged in 2024-07, with the labels that each got.

#21 [2024.07.23] feat/#14 코드 리뷰 기능 >> 게시글 생성/전체조회/단건조회/수정/삭제
  build.gradle
  docker-compose-minio.yml
  http/코드 리뷰.http
  src/main/java/com/sparta/publicclassdev/domain/codereview/controller/CodeReviewsController.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsDetailResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsListResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsRequestDto.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/entity/CodeReview.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/entity/CodeReviewComment.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/entity/CodeReviews.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/repository/CodeReviewsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/util/SizingConstants.java
  src/main/java/com/sparta/publicclassdev/global/config/MinioConfig.java
  src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
Labels: feat

#23 [Task] 신규 기능 entity생성 및 연관관계 설정 #4
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRoomUsers.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRooms.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/Messages.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/entity/Like.java
  src/main/java/com/sparta/publicclassdev/domain/group/entity/Cards.java
  src/main/java/com/sparta/publicclassdev/domain/group/entity/ChatRoom.java
  src/main/java/com/sparta/publicclassdev/domain/group/entity/ChatRoomUser.java
  src/main/java/com/sparta/publicclassdev/domain/group/entity/GroupInfo.java
  src/main/java/com/sparta/publicclassdev/domain/group/entity/GroupUser.java
  src/main/java/com/sparta/publicclassdev/domain/group/entity/Message.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/TeamUsers.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
  src/main/java/com/sparta/publicclassdev/domain/users/entity/Users.java
  src/main/java/com/sparta/publicclassdev/domain/winners/entity/Winners.java
Labels: feat

#34 [Task] 팀 매칭기능 구현 #24
  build.gradle
  http/팀매칭.http
  src/main/java/com/sparta/publicclassdev/PublicClassDevApplication.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/Messages.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
  src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
  src/main/java/com/sparta/publicclassdev/domain/teams/dto/TeamCreatesResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/TeamUsers.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
  src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
Labels: feat

#48 [2024-07-24] feat/#47 코드리뷰 기능 권한별 기능 Refactor
  http/코드 리뷰.http
  src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
  src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/service/CodeReviewCommentsService.java
Labels: refactor

#52 [2024-07-25] refactor: Code Review 게시글 단건 조회시 게시글 내용 필드 누락 추가
  src/main/java/com/sparta/publicclassdev/domain/codereview/dto/CodeReviewsDetailResponseDto.java
Labels: refactor

#54 [Task] 팀 이름 랜덤 생성 및 실시간 채팅 구현 #44
  build.gradle
  http/팀매칭.http
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/controller/ChatRoomsController.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/dto/ChatRoomsDto.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRoomUsers.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/ChatRooms.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/entity/Messages.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/ChatRoomUsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/ChatRoomsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/repository/MessagesRepository.java
  src/main/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsService.java
  src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
  src/main/java/com/sparta/publicclassdev/domain/teams/dto/TeamResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/TeamUsers.java
  src/main/java/com/sparta/publicclassdev/domain/teams/entity/Teams.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
  src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
  src/main/java/com/sparta/publicclassdev/global/config/WebSocketConfig.java
  src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
  src/test/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsServiceTest.java
Labels: feat

#61 [24-07-26] fix/#60 메서드 이름 오타 수정
  src/main/java/com/sparta/publicclassdev/domain/codereview/controller/CodeReviewsController.java
  src/main/java/com/sparta/publicclassdev/domain/codereview/service/CodeReviewsService.java
  src/main/java/com/sparta/publicclassdev/domain/codereviewcomment/controller/CodeReviewCommentsController.java
Labels: refactor

#66 [Task] Spring batch를 이용한 문제 출제 구현 #56
  http/user.http
  http/코드카타.http
  src/main/java/com/sparta/publicclassdev/PublicClassDevApplication.java
  src/main/java/com/sparta/publicclassdev/batch/config/BatchConfig.java
  src/main/java/com/sparta/publicclassdev/batch/tasklet/DailyCodeKataTasklet.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/controller/CodeKatasController.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/dto/CodeKatasDto.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/repository/CodeKatasRepository.java
  src/main/java/com/sparta/publicclassdev/domain/codekatas/service/CodeKatasService.java
  src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
  src/main/java/com/sparta/publicclassdev/global/exception/ErrorCode.java
  src/main/java/com/sparta/publicclassdev/global/security/SecurityUtil.java
  src/main/java/com/sparta/publicclassdev/quartz/config/QuartzConfig.java
  src/main/java/com/sparta/publicclassdev/quartz/job/DailyCodeKataJob.java
  src/test/java/com/sparta/publicclassdev/domain/chatrooms/service/ChatRoomsServiceTest.java
Labels: feat

#91 [Task] 명예의 전당 구현하기 #82
  http/코드 실행.http
  src/main/java/com/sparta/publicclassdev/domain/codekatas/entity/CodeKatas.java
  src/main/java/com/sparta/publicclassdev/domain/coderuns/repository/CodeRunsRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/controller/TeamsController.java
  src/main/java/com/sparta/publicclassdev/domain/teams/repository/TeamUsersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/teams/service/TeamsService.java
  src/main/java/com/sparta/publicclassdev/domain/winners/controller/WinnersController.java
  src/main/java/com/sparta/publicclassdev/domain/winners/dto/WinnersResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/winners/entity/Winners.java
  src/main/java/com/sparta/publicclassdev/domain/winners/repository/WinnersRepository.java
  src/main/java/com/sparta/publicclassdev/domain/winners/service/WinnersService.java
  src/main/java/com/sparta/publicclassdev/global/config/SchedulerConfig.java
  src/main/resources/logback-spring.xml
Labels: feat

#93 🩹 fix : dto 변경
  src/main/java/com/sparta/publicclassdev/domain/community/dto/CommunitiesResponseDto.java
  src/main/java/com/sparta/publicclassdev/domain/community/service/CommunitiesService.java
  src/main/java/com/sparta/publicclassdev/domain/communitycomments/dto/CommunityCommentResponseDto.java
Labels: fix
